// Seed 12 high-quality impact projects into MongoDB
require("dotenv").config();
const mongoose = require("mongoose");
const connectDB = require("./config/db");
const Project = require("./models/Project");

const PROJECTS = [
    {
        title: "Mangrove Restoration Program",
        description: "Restoring 500 hectares of mangrove forests along the coastline to protect biodiversity and sequester carbon.",
        fullDescription: "Mangroves are among the most carbon-dense ecosystems on Earth, storing up to 10× more carbon per hectare than tropical forests. This program works with local fishing communities to replant 500 hectares of degraded mangrove forests, protecting coastal villages from storm surges while creating sustainable livelihoods. The project trains 200 local workers in mangrove restoration and long-term forest management.",
        category: "environment",
        image: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80",
        fundingGoal: 75000,
        currentFunding: 54000,
        location: "Sundarbans, West Bengal, India",
        organization: "EcoRoots Foundation",
        verifiedType: "ngo",
        co2OffsetPerDollar: 0.8,
        co2Impact: "400 tons CO2 sequestered per year",
        donorCount: 342,
        featured: true,
        impactMetrics: [
            { label: "Hectares Restored", value: "500" },
            { label: "CO2 Sequestered", value: "400 tons/yr" },
            { label: "Jobs Created", value: "200" },
            { label: "Communities Benefited", value: "12" },
        ],
        tags: ["mangrove", "reforestation", "coastal", "carbon"],
    },
    {
        title: "Urban Air Quality Monitoring Network",
        description: "Deploying 150 low-cost air quality sensors across 15 cities to provide real-time pollution data for policy action.",
        fullDescription: "Air pollution causes over 7 million deaths annually. This initiative deploys a dense network of IoT-based air quality sensors across 15 Indian cities, providing real-time, hyper-local pollution data to citizens, urban planners, and health authorities. The open-data platform enables evidence-based policy interventions, school closure alerts, and targeted enforcement of emission standards.",
        category: "environment",
        image: "https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?w=800&q=80",
        fundingGoal: 45000,
        currentFunding: 18500,
        location: "Mumbai, Delhi, Bengaluru (15 cities)",
        organization: "CleanAir Labs",
        verifiedType: "gov",
        co2OffsetPerDollar: 0.3,
        co2Impact: "Enables 50,000 tons CO2 policy reductions",
        donorCount: 178,
        featured: false,
        impactMetrics: [
            { label: "Sensors Deployed", value: "150" },
            { label: "Cities Covered", value: "15" },
            { label: "Citizens Reached", value: "5M+" },
            { label: "Data Points/Day", value: "216,000" },
        ],
        tags: ["air quality", "IoT", "pollution", "smart city"],
    },
    {
        title: "Solar Microgrid Villages",
        description: "Bringing clean solar electricity to 30 off-grid villages with a total of 8,000 households.",
        fullDescription: "Over 1.2 billion people globally still lack access to reliable electricity. This project installs solar microgrids in 30 off-grid villages across rural Rajasthan, providing each household with 24/7 clean power for lighting, cooking, and small appliances. The microgrids create village-level energy cooperatives managed by trained local women, ensuring long-term sustainability and community ownership.",
        category: "environment",
        image: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&q=80",
        fundingGoal: 120000,
        currentFunding: 98000,
        location: "Rural Rajasthan, India",
        organization: "SunPower Cooperative",
        verifiedType: "gov",
        co2OffsetPerDollar: 1.2,
        co2Impact: "1,800 tons CO2 avoided per year",
        donorCount: 891,
        featured: true,
        impactMetrics: [
            { label: "Villages Electrified", value: "30" },
            { label: "Households Powered", value: "8,000" },
            { label: "CO2 Avoided/Year", value: "1,800 tons" },
            { label: "Women Energy Managers", value: "60" },
        ],
        tags: ["solar", "energy", "rural", "women empowerment"],
    },
    {
        title: "Plastic Recycling Innovation Hub",
        description: "Building a community plastic recycling center that converts plastic waste into construction materials.",
        fullDescription: "India generates ~26,000 tons of plastic waste daily, yet only captures 60% for recycling. This hub processes 5 tons of plastic waste per day, converting it into eco-bricks, roof tiles, and road construction materials using upcycling technology. The hub creates 150 dignified waste-picker jobs, provides health insurance, and runs technical training programs. Revenue from products funds operations sustainably.",
        category: "environment",
        image: "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=800&q=80",
        fundingGoal: 60000,
        currentFunding: 41200,
        location: "Pune, Maharashtra, India",
        organization: "CircleGreen NGO",
        verifiedType: "ngo",
        co2OffsetPerDollar: 0.6,
        co2Impact: "360 tons of plastic diverted from landfill per year",
        donorCount: 267,
        featured: false,
        impactMetrics: [
            { label: "Plastic Processed", value: "5 tons/day" },
            { label: "Jobs Created", value: "150" },
            { label: "Products Made", value: "Eco-bricks, tiles, road material" },
            { label: "Waste Diverted/Year", value: "1,825 tons" },
        ],
        tags: ["plastic", "recycling", "circular economy", "waste"],
    },
    {
        title: "Smart Rainwater Harvesting Network",
        description: "Installing 2,000 household-level rainwater harvesting systems with IoT monitoring in water-stressed districts.",
        fullDescription: "Over 600 million Indians face high-to-extreme water stress. This project installs IoT-enabled rooftop rainwater harvesting systems across 2,000 homes in water-stressed Bundelkhand, recharging groundwater and providing a supplementary water source during dry seasons. A mobile app allows households to monitor water levels, quality, and usage in real time. The project also trains local plumbers for installation and maintenance.",
        category: "infrastructure",
        image: "https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=800&q=80",
        fundingGoal: 55000,
        currentFunding: 22000,
        location: "Bundelkhand, Uttar Pradesh, India",
        organization: "WaterWise Foundation",
        verifiedType: "gov",
        co2OffsetPerDollar: 0.15,
        co2Impact: "Reduces energy-intensive water pumping by 60%",
        donorCount: 143,
        featured: false,
        impactMetrics: [
            { label: "Households Covered", value: "2,000" },
            { label: "Water Saved/Year", value: "50M litres" },
            { label: "Groundwater Recharged", value: "10M litres" },
            { label: "Local Jobs", value: "40 plumbers trained" },
        ],
        tags: ["water", "IoT", "groundwater", "infrastructure"],
    },
    {
        title: "Electric Bus Transition Project",
        description: "Converting 100 diesel public buses to electric in Tier-2 cities, reducing urban air pollution and CO2 emissions.",
        fullDescription: "Urban diesel buses are major contributors to particulate matter (PM2.5) and greenhouse gas emissions. This project converts 100 diesel buses to electric in three Tier-2 Indian cities, installing the necessary charging infrastructure at existing depots. The project partners with local bus authorities for operational integration and provides driver training for 500 bus operators. Expected to reduce PM2.5 emissions by 40% in targeted corridors.",
        category: "infrastructure",
        image: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&q=80",
        fundingGoal: 200000,
        currentFunding: 134000,
        location: "Nagpur, Coimbatore, Jaipur, India",
        organization: "GreenMobility India",
        verifiedType: "gov",
        co2OffsetPerDollar: 0.9,
        co2Impact: "12,000 tons CO2 avoided per year",
        donorCount: 512,
        featured: true,
        impactMetrics: [
            { label: "Buses Converted", value: "100" },
            { label: "CO2 Avoided/Year", value: "12,000 tons" },
            { label: "PM2.5 Reduction", value: "40%" },
            { label: "Drivers Trained", value: "500" },
        ],
        tags: ["electric", "transport", "urban", "air quality"],
    },
    {
        title: "Rural Telemedicine Centers",
        description: "Establishing 50 telemedicine centers in remote villages connecting patients to specialist doctors via video consultation.",
        fullDescription: "India has a doctor-to-patient ratio of 0.7 per 1,000 — well below the WHO recommended 1:1,000. Rural populations must travel hours to reach specialists. This project establishes 50 digital health hubs in remote villages, each equipped with diagnostic equipment (ECG, blood glucose, BP), a trained Community Health Worker, and high-speed internet for video consultations with specialist doctors in cities. Each hub serves approximately 500 households.",
        category: "healthcare",
        image: "https://images.unsplash.com/photo-1631815588090-d4bfec5b1ccb?w=800&q=80",
        fundingGoal: 90000,
        currentFunding: 13500,
        location: "Chhattisgarh & Jharkhand, India",
        organization: "HealthBridge Trust",
        verifiedType: "ngo",
        co2OffsetPerDollar: 0.05,
        co2Impact: "Eliminates 200,000 km of patient travel per year",
        donorCount: 89,
        featured: false,
        impactMetrics: [
            { label: "Telemedicine Hubs", value: "50" },
            { label: "Households Covered", value: "25,000" },
            { label: "Specialists Connected", value: "80+" },
            { label: "Consultations/Month", value: "5,000" },
        ],
        tags: ["healthcare", "telemedicine", "rural", "digital health"],
    },
    {
        title: "Green School Initiative",
        description: "Transforming 200 government schools with solar panels, rainwater harvesting, composting, and environmental curriculum.",
        fullDescription: "Schools are powerful platforms for environmental transformation. This initiative retrofits 200 government schools with rooftop solar panels, rainwater harvesting tanks, kitchen composting units, and school gardens. A new 3-hour environmental literacy curriculum is introduced, training 1,200 teachers and reaching 120,000 students. Schools generate surplus solar energy sold back to the grid, generating revenue for school programs. Each 'Green School' becomes a demonstration center for its community.",
        category: "education",
        image: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=800&q=80",
        fundingGoal: 80000,
        currentFunding: 57600,
        location: "Karnataka & Tamil Nadu, India",
        organization: "GreenFutures Education",
        verifiedType: "gov",
        co2OffsetPerDollar: 0.55,
        co2Impact: "800 tons CO2 offset from solar + 120,000 eco-students",
        donorCount: 433,
        featured: true,
        impactMetrics: [
            { label: "Schools Transformed", value: "200" },
            { label: "Students Reached", value: "120,000" },
            { label: "Teachers Trained", value: "1,200" },
            { label: "CO2 Offset/Year", value: "800 tons" },
        ],
        tags: ["education", "schools", "solar", "environment", "youth"],
    },
    {
        title: "Ocean Plastic Cleanup Fleet",
        description: "Deploying 10 solar-powered ocean cleanup vessels to collect plastic from coastal waters and river mouths.",
        fullDescription: "Over 8 million tons of plastic enters our oceans every year. This project deploys 10 solar-powered autonomous cleanup vessels equipped with AI-guided plastic detection systems in the most polluted coastal zones and river mouths of the Bay of Bengal. Collected plastic is sorted onshore and channeled to the Plastic Recycling Innovation Hub for upcycling. Real-time cleanup data is shared openly with researchers and policymakers globally.",
        category: "environment",
        image: "https://images.unsplash.com/photo-1618477460930-d8bffb5e2fe0?w=800&q=80",
        fundingGoal: 150000,
        currentFunding: 102000,
        location: "Bay of Bengal, Odisha & Andhra Pradesh",
        organization: "OceanGuard Alliance",
        verifiedType: "ngo",
        co2OffsetPerDollar: 0.7,
        co2Impact: "Prevents 500 tons of plastic from entering ocean per year",
        donorCount: 678,
        featured: true,
        impactMetrics: [
            { label: "Cleanup Vessels", value: "10" },
            { label: "Plastic Removed/Year", value: "500 tons" },
            { label: "Ocean Area Covered", value: "2,000 km²" },
            { label: "Species Protected", value: "Marine biodiversity" },
        ],
        tags: ["ocean", "plastic", "cleanup", "marine", "solar"],
    },
    {
        title: "Community Biogas Plants",
        description: "Building 100 community-level biogas plants converting organic waste into clean cooking fuel for rural households.",
        fullDescription: "Millions of Indian households cook on wood or dung fires, leading to severe indoor air pollution — India's second largest health hazard. This project constructs 100 community biogas plants, each serving 30–50 households with clean biogas from organic waste (kitchen scraps, crop residue, animal dung). The nutrient-rich slurry produced is used as organic fertilizer, replacing chemical fertilizers. Women who previously spent 4–6 hours daily collecting firewood are liberated for education and economic activity.",
        category: "environment",
        image: "https://images.unsplash.com/photo-1569172122301-bc5008bc09c5?w=800&q=80",
        fundingGoal: 40000,
        currentFunding: 38000,
        location: "Bihar & Madhya Pradesh, India",
        organization: "CleanCook India",
        verifiedType: "ngo",
        co2OffsetPerDollar: 1.1,
        co2Impact: "2,200 tons CO2 per year + eliminates indoor air pollution",
        donorCount: 892,
        featured: false,
        impactMetrics: [
            { label: "Biogas Plants", value: "100" },
            { label: "Households Served", value: "4,000" },
            { label: "CO2 Avoided/Year", value: "2,200 tons" },
            { label: "Women Hours Saved", value: "14,600 hrs/day" },
        ],
        tags: ["biogas", "clean cooking", "rural", "women", "bioenergy"],
    },
    {
        title: "Climate Resilient Agriculture",
        description: "Training 50,000 farmers in drought-resistant crops, water-smart irrigation, and agroforestry to climate-proof agriculture.",
        fullDescription: "Climate change threatens India's food security, with 60% of agriculture rain-fed and increasingly vulnerable to erratic monsoons. This project runs a 12-month training programme for 50,000 smallholder farmers on climate-smart agriculture: drought-resistant seed varieties, drip irrigation installation, soil carbon sequestration, and agroforestry integration. Farmer Producer Organizations (FPOs) are established for better market access and collective bargaining. Each farmer trained multiplies knowledge through peer-to-peer networks.",
        category: "education",
        image: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=800&q=80",
        fundingGoal: 100000,
        currentFunding: 62000,
        location: "Maharashtra, Gujarat & AP, India",
        organization: "AgriClimate Cooperative",
        verifiedType: "gov",
        co2OffsetPerDollar: 0.4,
        co2Impact: "1.2M tons CO2 sequestered through agroforestry",
        donorCount: 445,
        featured: false,
        impactMetrics: [
            { label: "Farmers Trained", value: "50,000" },
            { label: "Hectares Climate-Proofed", value: "150,000" },
            { label: "CO2 Sequestered", value: "1.2M tons over 10 yr" },
            { label: "Income Increase", value: "35% average" },
        ],
        tags: ["agriculture", "climate", "farmers", "food security", "agroforestry"],
    },
    {
        title: "Urban Vertical Farming Hub",
        description: "Establishing 5 vertical farms in urban food deserts, producing 50 tons of fresh vegetables per year without soil or sunlight.",
        fullDescription: "Urban food deserts leave millions without access to fresh, affordable vegetables. This project establishes 5 indoor vertical farms in Mumbai's low-income neighborhoods, using hydroponic growing towers, LED lighting, and 95% water recycling to produce 50 tons of leafy greens and vegetables per year. The farms are priced for affordability and staffed entirely by local youth trained in agri-tech. Surplus produce feeds school mid-day meal programs in the area.",
        category: "infrastructure",
        image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
        fundingGoal: 70000,
        currentFunding: 28000,
        location: "Mumbai, Maharashtra, India",
        organization: "UrbanGrow Collective",
        verifiedType: "ngo",
        co2OffsetPerDollar: 0.25,
        co2Impact: "Reduces food transport emissions by 80% vs imported produce",
        donorCount: 211,
        featured: false,
        impactMetrics: [
            { label: "Vertical Farms", value: "5" },
            { label: "Produce/Year", value: "50 tons" },
            { label: "Water Saved vs Traditional", value: "95%" },
            { label: "Youth Trained", value: "75" },
        ],
        tags: ["vertical farming", "urban food", "hydroponics", "youth", "infrastructure"],
    },
];

async function seed() {
    await connectDB();
    await Project.deleteMany({});
    const inserted = await Project.insertMany(PROJECTS);
    console.log(`✅ Seeded ${inserted.length} projects successfully.`);
    process.exit(0);
}

seed().catch(err => { console.error(err); process.exit(1); });
